puts "The students of my cohort at Makers Academy"
puts "------------------"
puts "Rachel Nolan"
puts "Tim Scully"
puts "Elena Garrone"
puts "Sandrine Madame"
puts "Andrew Hercules"
puts "Stephen Giles"
puts "Bernard Mordan"
puts "Nicole Pell"
puts "Yvette Cook"
puts "Faddie H"
puts "Anna Schechter"
puts "Schlap Alias"
puts "James Scarter"
puts "Karin Nielsen"
puts "Denise Yu"